export const GET_NOTE_TYPES = 'GET_NOTE_TYPES';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_INSPIRATIONS = 'GET_INSPIRATIONS';

export const GET_TAGS = 'GET_TAGS';
export const CREATE_TAG = 'CREATE_TAG';
export const CREATE_TAG_FAILED = 'CREATE_TAG_FAILED';

export const GET_NOTES = 'GET_NOTES';
export const CREATE_NOTE = 'CREATE_NOTE';
export const CREATE_NOTE_FAILED = 'CREATE_NOTE_FAILED';
export const EDIT_NOTE = 'EDIT_NOTE';
export const EDIT_NOTE_FAILED = 'EDIT_NOTE_FAILED';
export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_FAILED = 'DELETE_NOTE_FAILED';

export default {
  GET_NOTE_TYPES,
  GET_CATEGORIES,
  GET_TAGS,
  CREATE_TAG,
  CREATE_TAG_FAILED,
  GET_INSPIRATIONS,
  GET_NOTES,
  CREATE_NOTE,
  CREATE_NOTE_FAILED,
  EDIT_NOTE,
  EDIT_NOTE_FAILED,
  DELETE_NOTE,
  DELETE_NOTE_FAILED,
};
